package repositories

import (
	"database/sql"
	"errors"
	"fmt"

	"Most/database"
	"Most/internal/players/models"
)

// ErrPlayerNotFound is returned when no player has the requested player_id.
var ErrPlayerNotFound = errors.New("player not found")

// playerColumns is the single source of truth for reading a player row. The
// order must stay exactly the same as the Scan arguments in scanPlayer.
const playerColumns = `player_id,
	first_name,
		last_name,
		phone,
		date_of_birth,
		position,
		category,
		height_cm,
		weight_kg,
		preferred_foot,
		previous_team,
		profile_image`

// CreatePlayer inserts a new player row and returns the player_id generated by SQLite.
func CreatePlayer(player models.Player) (int64, error) {
	result, err := database.Database.Exec(
		`INSERT INTO player (
			first_name,
			last_name,
			phone,
			date_of_birth,
			position,
			category,
			height_cm,
			weight_kg,
			preferred_foot,
			previous_team,
			profile_image
		) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		player.FirstName,
		player.LastName,
		player.Phone,
		player.DateOfBirth,
		player.Position,
		player.Category,
		player.HeightCM,
		player.WeightKG,
		player.PreferredFoot,
		player.PreviousTeam,
		player.ProfileImage,
	)
	if err != nil {
		return 0, fmt.Errorf("can't insert player: %v", err)
	}

	playerID, err := result.LastInsertId()
	if err != nil {
		return 0, fmt.Errorf("can't read the generated player_id: %v", err)
	}

	return playerID, nil
}

// GetPlayers returns every player stored in the player table.
func GetPlayers() ([]models.Player, error) {
	rows, err := database.Database.Query(
		`SELECT ` + playerColumns + `
		FROM player
		ORDER BY player_id`,
	)
	if err != nil {
		return nil, fmt.Errorf("can't read players: %v", err)
	}
	defer rows.Close()

	players := []models.Player{}

	for rows.Next() {
		player, err := scanPlayer(rows)
		if err != nil {
			return nil, err
		}

		players = append(players, player)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("can't read players: %v", err)
	}

	return players, nil
}

// GetPlayerByID returns one player.
// It returns ErrPlayerNotFound when the player_id does not exist.
func GetPlayerByID(playerID int) (models.Player, error) {
	return scanPlayer(database.Database.QueryRow(
		`SELECT `+playerColumns+` FROM player WHERE player_id = ?`,
		playerID,
	))
}

// UpdatePlayer saves the editable fields of an existing player row.
// profile_image is left out on purpose: the image is handled by the upload
// flow, so an edit never overwrites it.
// It returns ErrPlayerNotFound when the player_id does not exist.
func UpdatePlayer(player models.Player) error {
	result, err := database.Database.Exec(
		`UPDATE player SET
			first_name = ?,
			last_name = ?,
			phone = ?,
			date_of_birth = ?,
			position = ?,
			category = ?,
			height_cm = ?,
			weight_kg = ?,
			preferred_foot = ?,
			previous_team = ?
		WHERE player_id = ?`,
		player.FirstName,
		player.LastName,
		player.Phone,
		player.DateOfBirth,
		player.Position,
		player.Category,
		player.HeightCM,
		player.WeightKG,
		player.PreferredFoot,
		player.PreviousTeam,
		player.PlayerID,
	)
	if err != nil {
		return fmt.Errorf("can't update player %d: %v", player.PlayerID, err)
	}

	changed, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("can't check updated player %d: %v", player.PlayerID, err)
	}
	if changed == 0 {
		return ErrPlayerNotFound
	}

	return nil
}

// scanner is implemented by both *sql.Row and *sql.Rows, so one reader works
// for a single player and for the list.
type scanner interface{ Scan(...any) error }

// scanPlayer reads one row selected with playerColumns.
func scanPlayer(row scanner) (models.Player, error) {
	var player models.Player
	// phone is nullable: the players created before migration 000004 have NULL.
	var phone sql.NullString

	if err := row.Scan(
		&player.PlayerID,
		&player.FirstName,
		&player.LastName,
		&phone,
		&player.DateOfBirth,
		&player.Position,
		&player.Category,
		&player.HeightCM,
		&player.WeightKG,
		&player.PreferredFoot,
		&player.PreviousTeam,
		&player.ProfileImage,
	); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return models.Player{}, ErrPlayerNotFound
		}
		return models.Player{}, fmt.Errorf("can't read player row: %v", err)
	}

	player.Phone = phone.String

	return player, nil
}

// DeletePlayer removes one player row and returns the profile_image path that was
// stored, so the caller can delete the image file too.
// It returns ErrPlayerNotFound when the player_id does not exist.
func DeletePlayer(playerID int) (string, error) {
	// read the image path first, we need it after the row is gone.
	// profile_image can be NULL, so we read it into sql.NullString.
	var profileImage sql.NullString

	if err := database.Database.QueryRow(
		`SELECT profile_image FROM player WHERE player_id = ?`,
		playerID,
	).Scan(&profileImage); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return "", ErrPlayerNotFound
		}
		return "", fmt.Errorf("can't find player %d: %v", playerID, err)
	}

	if _, err := database.Database.Exec(
		`DELETE FROM player WHERE player_id = ?`,
		playerID,
	); err != nil {
		return "", fmt.Errorf("can't delete player %d: %v", playerID, err)
	}

	return profileImage.String, nil
}
