package repositories

import (
	"fmt"

	"Most/database"
	"Most/internal/players/models"
)

// CreatePlayer inserts a new player row and returns the player_id generated by SQLite.
func CreatePlayer(player models.Player) (int64, error) {
	result, err := database.Database.Exec(
		`INSERT INTO player (
			first_name,
			last_name,
			date_of_birth,
			position,
			category,
			height_cm,
			weight_kg,
			preferred_foot,
			previous_team,
			profile_image
		) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		player.FirstName,
		player.LastName,
		player.DateOfBirth,
		player.Position,
		player.Category,
		player.HeightCM,
		player.WeightKG,
		player.PreferredFoot,
		player.PreviousTeam,
		player.ProfileImage,
	)
	if err != nil {
		return 0, fmt.Errorf("can't insert player: %v", err)
	}

	playerID, err := result.LastInsertId()
	if err != nil {
		return 0, fmt.Errorf("can't read the generated player_id: %v", err)
	}

	return playerID, nil
}
