package repositories

import (
	"database/sql"
	"errors"
	"fmt"

	"Most/database"
	"Most/internal/players/models"
)

// ErrPlayerNotFound is returned when no player has the requested player_id.
var ErrPlayerNotFound = errors.New("player not found")

// CreatePlayer inserts a new player row and returns the player_id generated by SQLite.
func CreatePlayer(player models.Player) (int64, error) {
	result, err := database.Database.Exec(
		`INSERT INTO player (
			first_name,
			last_name,
			date_of_birth,
			position,
			category,
			height_cm,
			weight_kg,
			preferred_foot,
			previous_team,
			profile_image
		) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		player.FirstName,
		player.LastName,
		player.DateOfBirth,
		player.Position,
		player.Category,
		player.HeightCM,
		player.WeightKG,
		player.PreferredFoot,
		player.PreviousTeam,
		player.ProfileImage,
	)
	if err != nil {
		return 0, fmt.Errorf("can't insert player: %v", err)
	}

	playerID, err := result.LastInsertId()
	if err != nil {
		return 0, fmt.Errorf("can't read the generated player_id: %v", err)
	}

	return playerID, nil
}

// GetPlayers returns every player stored in the player table.
func GetPlayers() ([]models.Player, error) {
	rows, err := database.Database.Query(
		`SELECT
			player_id,
			first_name,
			last_name,
			date_of_birth,
			position,
			category,
			height_cm,
			weight_kg,
			preferred_foot,
			previous_team,
			profile_image
		FROM player
		ORDER BY player_id`,
	)
	if err != nil {
		return nil, fmt.Errorf("can't read players: %v", err)
	}
	defer rows.Close()

	players := []models.Player{}

	for rows.Next() {
		var player models.Player

		if err := rows.Scan(
			&player.PlayerID,
			&player.FirstName,
			&player.LastName,
			&player.DateOfBirth,
			&player.Position,
			&player.Category,
			&player.HeightCM,
			&player.WeightKG,
			&player.PreferredFoot,
			&player.PreviousTeam,
			&player.ProfileImage,
		); err != nil {
			return nil, fmt.Errorf("can't read player row: %v", err)
		}

		players = append(players, player)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("can't read players: %v", err)
	}

	return players, nil
}

// DeletePlayer removes one player row and returns the profile_image path that was
// stored, so the caller can delete the image file too.
// It returns ErrPlayerNotFound when the player_id does not exist.
func DeletePlayer(playerID int) (string, error) {
	// read the image path first, we need it after the row is gone.
	// profile_image can be NULL, so we read it into sql.NullString.
	var profileImage sql.NullString

	if err := database.Database.QueryRow(
		`SELECT profile_image FROM player WHERE player_id = ?`,
		playerID,
	).Scan(&profileImage); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return "", ErrPlayerNotFound
		}
		return "", fmt.Errorf("can't find player %d: %v", playerID, err)
	}

	if _, err := database.Database.Exec(
		`DELETE FROM player WHERE player_id = ?`,
		playerID,
	); err != nil {
		return "", fmt.Errorf("can't delete player %d: %v", playerID, err)
	}

	return profileImage.String, nil
}
