// Package services holds the player business rules: it validates what the
// handlers read from the request before anything reaches the repository.
package services

import (
	"errors"
	"fmt"
	"strings"
	"time"

	"Most/internal/players/models"
	"Most/internal/players/repositories"
)

// ErrInvalidInput is returned when the data sent by the client is wrong.
var ErrInvalidInput = errors.New("invalid player input")

// ErrPlayerNotFound is re-exported from the repository so the handlers only
// need this package and never talk to the repository directly.
var ErrPlayerNotFound = repositories.ErrPlayerNotFound

// Bounds of the physical fields, shared by the create and the update flow.
const (
	MinHeightCM = 50
	MaxHeightCM = 250
	MinWeightKG = 5
	MaxWeightKG = 200
	// MaxPhoneLength is the biggest phone number we accept.
	MaxPhoneLength = 25
)

// dateLayouts are the date_of_birth formats accepted from the frontend.
var dateLayouts = []string{
	"2006-01-02",
	time.RFC3339,
	"2006-01-02T15:04:05",
	"2006-01-02 15:04:05",
}

// UpdateInput holds the editable fields of a player. Every field is optional
// (a pointer), so only what the client sends is changed. That is why sending
// just {"phone": "0612345678"} leaves all the other columns untouched.
type UpdateInput struct {
	FirstName     *string  `json:"first_name"`
	LastName      *string  `json:"last_name"`
	Phone         *string  `json:"phone"`
	DateOfBirth   *string  `json:"date_of_birth"`
	Position      *string  `json:"position"`
	Category      *string  `json:"category"`
	HeightCM      *int     `json:"height_cm"`
	WeightKG      *float64 `json:"weight_kg"`
	PreferredFoot *string  `json:"preferred_foot"`
	PreviousTeam  *string  `json:"previous_team"`
}

// CreatePlayer validates the player and saves it, then returns it with the
// player_id generated by SQLite.
func CreatePlayer(player models.Player) (models.Player, error) {
	player.FirstName = strings.TrimSpace(player.FirstName)
	player.LastName = strings.TrimSpace(player.LastName)
	player.Phone = NormalizePhone(player.Phone)
	player.Position = strings.TrimSpace(player.Position)
	player.Category = strings.TrimSpace(player.Category)
	player.PreferredFoot = strings.TrimSpace(player.PreferredFoot)
	player.PreviousTeam = strings.TrimSpace(player.PreviousTeam)

	if err := ValidatePlayer(player); err != nil {
		return models.Player{}, err
	}

	playerID, err := repositories.CreatePlayer(player)
	if err != nil {
		return models.Player{}, err
	}
	player.PlayerID = int(playerID)

	return player, nil
}

// GetPlayers returns every player.
func GetPlayers() ([]models.Player, error) {
	return repositories.GetPlayers()
}

// GetPlayerByID returns one player.
func GetPlayerByID(playerID int) (models.Player, error) {
	return repositories.GetPlayerByID(playerID)
}

// UpdatePlayer applies the received fields on the stored player and saves it.
func UpdatePlayer(playerID int, input UpdateInput) (models.Player, error) {
	player, err := repositories.GetPlayerByID(playerID)
	if err != nil {
		return models.Player{}, err
	}

	if input.FirstName != nil {
		player.FirstName = strings.TrimSpace(*input.FirstName)
	}
	if input.LastName != nil {
		player.LastName = strings.TrimSpace(*input.LastName)
	}
	if input.Phone != nil {
		player.Phone = NormalizePhone(*input.Phone)
	}
	if input.DateOfBirth != nil {
		dateOfBirth, err := ParseDateOfBirth(strings.TrimSpace(*input.DateOfBirth))
		if err != nil {
			return models.Player{}, err
		}
		player.DateOfBirth = dateOfBirth
	}
	if input.Position != nil {
		player.Position = strings.TrimSpace(*input.Position)
	}
	if input.Category != nil {
		player.Category = strings.TrimSpace(*input.Category)
	}
	if input.HeightCM != nil {
		player.HeightCM = *input.HeightCM
	}
	if input.WeightKG != nil {
		player.WeightKG = *input.WeightKG
	}
	if input.PreferredFoot != nil {
		player.PreferredFoot = strings.TrimSpace(*input.PreferredFoot)
	}
	if input.PreviousTeam != nil {
		player.PreviousTeam = strings.TrimSpace(*input.PreviousTeam)
	}

	if err := ValidatePlayer(player); err != nil {
		return models.Player{}, err
	}

	if err := repositories.UpdatePlayer(player); err != nil {
		return models.Player{}, err
	}

	return repositories.GetPlayerByID(playerID)
}

// DeletePlayer removes one player and returns the stored profile_image path,
// so the caller can delete the image file too.
func DeletePlayer(playerID int) (string, error) {
	return repositories.DeletePlayer(playerID)
}

// ValidatePlayer checks the fields the client is allowed to send.
// A phone is optional: the players created before the phone column existed
// simply have none.
func ValidatePlayer(player models.Player) error {
	if player.FirstName == "" {
		return fmt.Errorf("%w: first_name is required", ErrInvalidInput)
	}
	if player.LastName == "" {
		return fmt.Errorf("%w: last_name is required", ErrInvalidInput)
	}
	if player.DateOfBirth.IsZero() {
		return fmt.Errorf("%w: date_of_birth is required", ErrInvalidInput)
	}
	if player.HeightCM != 0 && (player.HeightCM < MinHeightCM || player.HeightCM > MaxHeightCM) {
		return fmt.Errorf("%w: height_cm must be a number between %d and %d", ErrInvalidInput, MinHeightCM, MaxHeightCM)
	}
	if player.WeightKG != 0 && (player.WeightKG < MinWeightKG || player.WeightKG > MaxWeightKG) {
		return fmt.Errorf("%w: weight_kg must be a number between %d and %d", ErrInvalidInput, MinWeightKG, MaxWeightKG)
	}
	return ValidatePhone(player.Phone)
}

// NormalizePhone only removes the spaces around the number. The value stays a
// string so a leading zero or a country code like +212 is never lost.
func NormalizePhone(value string) string {
	return strings.TrimSpace(value)
}

// ValidatePhone keeps the check simple: a phone number is a free string, we
// only make sure it is short enough and holds no unexpected character.
func ValidatePhone(phone string) error {
	if phone == "" {
		return nil
	}
	if len(phone) > MaxPhoneLength {
		return fmt.Errorf("%w: phone must be at most %d characters", ErrInvalidInput, MaxPhoneLength)
	}
	for position, char := range phone {
		switch {
		case char >= '0' && char <= '9':
		case char == '+', char == '-', char == ' ', char == '(', char == ')', char == '.':
		default:
			return fmt.Errorf("%w: phone has an unexpected character at position %d", ErrInvalidInput, position+1)
		}
	}
	return nil
}

// ParseDateOfBirth converts a received date_of_birth into a time.Time.
func ParseDateOfBirth(value string) (time.Time, error) {
	for _, layout := range dateLayouts {
		if parsed, err := time.Parse(layout, value); err == nil {
			return parsed, nil
		}
	}
	return time.Time{}, fmt.Errorf("%w: date_of_birth is invalid, use the format YYYY-MM-DD", ErrInvalidInput)
}
